const data = [
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 22.png",
    gender: "unisex",
    star: 3,
    rating: 10,
    price: 594.33,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 41.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 999,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 29.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 538,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 30.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 800,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 31.png",
    gender: "unisex",
    star: 3,
    rating: 10,
    price: 594.33,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 49.png",
    gender: "male",
    star: 5,
    rating: 10,
    price: 100.99,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 48.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 40.77,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 50.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 2000,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 47.png",
    gender: "unisex",
    star: 3,
    rating: 10,
    price: 594.33,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 46.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 999,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 45.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 538,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 44.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 800,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 43.png",
    gender: "male",
    star: 5,
    rating: 10,
    price: 100.99,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 47.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 40.77,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 41.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 2000,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 45.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 538,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 44.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 800,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 43.png",
    gender: "male",
    star: 5,
    rating: 10,
    price: 100.99,
  },
  {
    productName: " Rolex watch",
    productImg: "./Rectangle 47.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 40.77,
  },
];

export default data;
