const data = [
  {
    productName: "Rolex watch",
    productImg: "./Rectangle 22.png",
    gender: "unisex",
    star: 3,
    rating: 10,
    price: 594.33,
  },
  {
    productName: "Winter shirt",
    productImg: "./Rectangle 41.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 999,
  },
  {
    productName: "Nike sneakers",
    productImg: "./Rectangle 29.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 538,
  },
  {
    productName: "Addidas",
    productImg: "./Rectangle 30.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 800,
  },
  {
    productName: "Swiss Jeans",
    productImg: "./Rectangle 31.png",
    gender: "unisex",
    star: 3,
    rating: 10,
    price: 594.33,
  },
  {
    productName: "Louis vuitton",
    productImg: "./Rectangle 49.png",
    gender: "male",
    star: 5,
    rating: 10,
    price: 100.99,
  },
  {
    productName: "Kinetix shirts",
    productImg: "./Rectangle 48.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 40.77,
  },
  {
    productName: "Flower dress",
    productImg: "./Rectangle 50.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 2000,
  },
  {
    productName: "Next leather loafer",
    productImg: "./Rectangle 47.png",
    gender: "male",
    star: 3,
    rating: 10,
    price: 594.33,
  },
  {
    productName: "Zara shoe",
    productImg: "./Rectangle 46.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 999,
  },
  {
    productName: "Next shirts",
    productImg: "./Rectangle 45.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 538,
  },
  {
    productName: "Brown suede brogue",
    productImg: "./Rectangle 44.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 800,
  },
  {
    productName: "Nike shoe",
    productImg: "./Rectangle 43.png",
    gender: "male",
    star: 5,
    rating: 10,
    price: 100.99,
  },
  {
    productName: "Nike shoe",
    productImg: "./nick_air.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 40.77,
  },
  {
    productName: "Nike Black",
    productImg: "./nick_black.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 40.77,
  },
  {
    productName: "Swiss silver watch",
    productImg: "./swiss_watch.png",
    gender: "male",
    star: 4,
    rating: 10,
    price: 538,
  },
  {
    productName: "ladies wears",
    productImg: "./ladies_wears.png",
    gender: "female",
    star: 4,
    rating: 10,
    price: 800,
  },
  {
    productName: "Nick watch.png",
    productImg: "./Nick_watch.png",
    gender: "male",
    star: 5,
    rating: 10,
    price: 100.99,
  },
];

export default data;
